#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Rodada J — conversão de quizzes para múltipla escolha, parte 2 (m12 a m21).
m17 (Glossário Técnico) não tem quizzes.
"""
import json

def opt(i, t): return {"id": i, "text": t}
def Q(text, options, correct, explanation):
    return {"text": text, "options": options, "correct": correct, "explanation": explanation}

CONVERTED = {}

CONVERTED["m12"] = [
    Q("Por que a forma de onda no tempo é mais adequada do que o espectro para confirmar um dente de engrenagem trincado?",
      [opt("a","Porque o impacto é um evento discreto e breve que aparece como pico isolado e nítido no tempo, revelando diretamente o eixo/engrenagem problemático; no espectro essa energia se espalha em 1X, na frequência natural excitada e em bandas laterais."),
       opt("b","Porque o espectro não é capaz de medir frequências acima de 1X RPM."),
       opt("c","Porque a forma de onda no tempo tem resolução em frequência maior que o espectro FFT."),
       opt("d","Porque dentes trincados só produzem vibração em direção axial, nunca radial.")],
      "a",
      "O impacto de um dente trincado é um evento discreto e breve no tempo; na forma de onda aparece como pico isolado e nítido, com o tempo entre impactos revelando diretamente qual eixo/engrenagem está com problema. No espectro, essa mesma energia se espalha em 1X RPM, na frequência natural excitada e em bandas laterais, tornando o diagnóstico mais indireto."),
    Q("Um rotor apresenta 1X RPM elevado, fase estável e repetível entre medições sucessivas, e diferença de fase de ~90° entre horizontal e vertical no mesmo mancal. Isso é mais consistente com desbalanceamento ou com folga?",
      [opt("a","Desbalanceamento — fase estável e repetível indica fenômeno síncrono coerente com a rotação; a diferença de ~90° entre H e V é o padrão esperado para o movimento circular/elíptico gerado pela força centrífuga."),
       opt("b","Folga — fase estável é a assinatura clássica de folga mecânica."),
       opt("c","Desalinhamento — a diferença de 90° entre H e V só ocorre em desalinhamento angular."),
       opt("d","Não é possível diferenciar sem medir também a direção axial.")],
      "a",
      "É mais consistente com desbalanceamento: a fase estável e repetível indica um fenômeno síncrono e coerente com a rotação (força centrífuga girando junto ao eixo), e a diferença de ~90° entre horizontal e vertical é o padrão esperado para o movimento circular/elíptico gerado por essa força. A folga mecânica produziria fase instável e não repetível."),
]

CONVERTED["m13"] = [
    Q("Por que dados geométricos de rolamentos e engrenagens devem ser registrados na ficha técnica da máquina antes de ocorrer qualquer problema?",
      [opt("a","Porque o cálculo das frequências de defeito (BPFO, BPFI, BSF, FTF, GMF) depende de dados geométricos que são muito mais difíceis de obter durante uma emergência de falha do que durante o cadastro planejado da máquina."),
       opt("b","Porque a norma ISO 10816 exige esse cadastro como condição legal para operar a máquina."),
       opt("c","Porque sem esses dados o sensor de vibração simplesmente não funciona."),
       opt("d","Porque o fabricante cobra uma taxa extra caso os dados sejam solicitados depois da instalação.")],
      "a",
      "O cálculo das frequências de defeito (BPFO, BPFI, BSF, FTF) e da frequência de engrenamento (GMF) depende de dados geométricos específicos (número de elementos, diâmetros, ângulo de contato, número de dentes) muito mais difíceis de obter durante uma emergência de falha do que durante o cadastro planejado no programa de monitoramento."),
    Q("Quais elementos não podem faltar em um bom relatório de diagnóstico de vibração?",
      [opt("a","Identificação da máquina/ponto e condição operacional; classificação de severidade segundo norma aplicável (ISO 10816); diagnóstico de causa provável com evidências (espectro, fase, forma de onda); recomendação de ação com prazo sugerido."),
       opt("b","Apenas o valor RMS de velocidade medido, sem necessidade de contexto adicional."),
       opt("c","Apenas fotos da máquina, sem necessidade de dados numéricos."),
       opt("d","Apenas o nome do técnico responsável e a data da medição.")],
      "a",
      "Um bom relatório deve conter: identificação da máquina/ponto e condição operacional no momento da medição; classificação de severidade segundo a norma aplicável (ISO 10816); diagnóstico da causa provável com as evidências que o sustentam; e a recomendação de ação com prazo sugerido."),
]

CONVERTED["m14"] = [
    Q("Por que é necessário subtrair vetorialmente O de O+T no balanceamento de campo, em vez de subtrair apenas as amplitudes (escalares)?",
      [opt("a","Porque a vibração é uma grandeza vetorial (amplitude e fase); só a subtração vetorial completa isola corretamente o efeito do peso de teste, já que a soma vetorial de O e do efeito do peso é o que gera a leitura combinada O+T."),
       opt("b","Porque a subtração escalar é proibida por norma técnica, independentemente do resultado numérico."),
       opt("c","Porque amplitudes de vibração nunca podem ser subtraídas, apenas somadas."),
       opt("d","Porque o efeito do peso de teste é sempre igual à amplitude de O, tornando a subtração escalar redundante.")],
      "a",
      "A vibração é uma grandeza vetorial (amplitude e fase/direção); o efeito isolado do peso de teste só pode ser isolado corretamente subtraindo os dois vetores completos, pois a soma vetorial de O e do efeito do peso de teste é o que gera a leitura combinada O+T — uma subtração escalar ignoraria a fase e levaria a cálculos incorretos de massa e ângulo."),
    Q("Durante um balanceamento, a fase da vibração varia de forma instável e não repetível entre medições sucessivas. O que isso sugere, e o que deve ser verificado antes de prosseguir?",
      [opt("a","Sugere possível ressonância próxima ou folga mecânica mascarando o sinal; deve-se verificar (ex.: teste de impacto) se a rotação de balanceamento está próxima de uma frequência natural e descartar outras causas de instabilidade de fase antes de prosseguir."),
       opt("b","Sugere que o peso de teste está incorreto; basta trocar o peso e prosseguir normalmente."),
       opt("c","Sugere excesso de precisão do equipamento de medição, sem necessidade de nenhuma verificação adicional."),
       opt("d","É comportamento normal e esperado em todo balanceamento de campo, sem implicação diagnóstica.")],
      "a",
      "Fase instável e não repetível é sinal de possível ressonância próxima ou de outra não linearidade (como folga mecânica) mascarando o sinal de desbalanceamento. Antes de prosseguir, deve-se verificar se a rotação de balanceamento está próxima de uma frequência natural e descartar/corrigir outras causas de instabilidade, já que o balanceamento não é confiável nessas condições."),
    Q("Um peso de teste de 10 g produziu um efeito |T| de apenas 0,3 mm/s, pequeno demais para calcular com confiança o ângulo de correção. O que deve ser feito?",
      [opt("a","Aumentar a massa do peso de teste (dentro de limites seguros) e repetir a medição, obtendo um efeito |T| grande o suficiente para uma fase bem definida e um cálculo confiável."),
       opt("b","Ignorar o resultado e aplicar diretamente a massa e o ângulo calculados com o peso original."),
       opt("c","Reduzir ainda mais a massa do peso de teste, já que pesos menores sempre aumentam a precisão."),
       opt("d","Interromper definitivamente o balanceamento, pois um efeito pequeno significa que o rotor não pode ser balanceado.")],
      "a",
      "Deve-se aumentar a massa do peso de teste (dentro de limites seguros para o rotor) e repetir a medição, de forma a obter um efeito |T| suficientemente grande (e portanto uma fase suficientemente bem definida) para que o cálculo do ângulo e da massa de correção seja confiável — um efeito muito pequeno amplifica o erro relativo de medição."),
]

CONVERTED["m15"] = [
    Q("Por que o pé-manco (soft foot) deve ser verificado e corrigido antes de iniciar o alinhamento de um eixo?",
      [opt("a","Porque um pé frouxo faz a carcaça se deformar de maneira diferente a cada aperto dos parafusos, tornando qualquer medição de alinhamento sobre essa base instável não repetível."),
       opt("b","Porque o soft foot afeta apenas a temperatura da máquina, não o alinhamento em si."),
       opt("c","Porque a norma de alinhamento proíbe explicitamente máquinas com qualquer tipo de pé de apoio."),
       opt("d","Porque corrigir o soft foot elimina completamente a necessidade de balanceamento posterior.")],
      "a",
      "Um pé frouxo faz com que a carcaça da máquina se deforme de maneira diferente cada vez que os parafusos de fixação são apertados — qualquer medição de alinhamento feita sobre essa base instável não é repetível e pode indicar uma correção que muda assim que os parafusos são reapertados de forma diferente."),
    Q("Um redutor apresenta correção necessária de +0,40 mm no pé dianteiro e +0,42 mm no traseiro (mesmo sinal, valores próximos). Isso é mais consistente com offset paralelo ou desvio angular?",
      [opt("a","Offset paralelo — correções de mesmo sinal e magnitude semelhante nos dois pés indicam deslocamento praticamente uniforme ao longo do eixo, com pouca contribuição angular."),
       opt("b","Desvio angular — qualquer correção positiva nos dois pés indica sempre um problema angular."),
       opt("c","Nenhum dos dois — valores tão próximos indicam erro de medição, sem problema real de alinhamento."),
       opt("d","Ambos em igual proporção, já que a diferença entre os valores é sempre irrelevante.")],
      "a",
      "Correções de mesmo sinal e magnitude semelhante nos dois pés indicam um deslocamento praticamente uniforme ao longo do eixo — predominantemente offset paralelo, com pouca contribuição angular (que produziria uma diferença proporcional à distância entre os pés)."),
    Q("Por que algumas máquinas de alta temperatura são deliberadamente alinhadas \"fora da tolerância\" a frio?",
      [opt("a","Porque em operação os componentes se expandem termicamente e mudam de posição; alinhar fora do esquadro a frio, na direção oposta ao crescimento térmico esperado, compensa esse efeito, ficando dentro da tolerância na temperatura normal de operação."),
       opt("b","Porque instrumentos de alinhamento a laser só funcionam corretamente fora da tolerância padrão."),
       opt("c","Porque a norma de alinhamento exige uma margem de erro proposital em todas as máquinas de alta temperatura."),
       opt("d","Porque isso reduz o tempo de instalação, independentemente do comportamento térmico da máquina.")],
      "a",
      "Em operação, componentes de alta temperatura se expandem termicamente e mudam de posição em relação à condição fria de montagem. Alinhar intencionalmente \"fora do esquadro\" a frio, na direção oposta ao crescimento térmico esperado, compensa esse efeito, de forma que o alinhamento fique dentro da tolerância exatamente na temperatura normal de operação."),
]

CONVERTED["m16"] = [
    Q("No Caso 1, por que a fase (e não apenas a amplitude do espectro) foi decisiva para diferenciar desalinhamento de desbalanceamento?",
      [opt("a","Porque ambos podem gerar picos em 1X e 2X; a diferença de fase próxima de 180° através do acoplamento, medida axialmente, é a evidência que discrimina desalinhamento de outras hipóteses com espectro parecido."),
       opt("b","Porque a amplitude do espectro é sempre idêntica nos dois casos, tornando a fase a única variável disponível."),
       opt("c","Porque o desbalanceamento nunca produz picos em 1X, apenas o desalinhamento."),
       opt("d","Porque a fase só pode ser medida quando há desalinhamento presente na máquina.")],
      "a",
      "Tanto o desalinhamento quanto certas formas de desbalanceamento podem gerar picos em 1X e 2X; a diferença de fase próxima de 180° através do acoplamento, medida axialmente, é a evidência que discrimina desalinhamento de outras hipóteses com espectro superficialmente parecido."),
    Q("No Caso 3, por que a amplitude de GMF isoladamente seria uma métrica enganosa para acompanhar a evolução do defeito de folga ao longo do tempo?",
      [opt("a","Porque a amplitude de GMF diminui com o aumento de carga (o jogo se absorve sob carga); comparar leituras em cargas diferentes levaria a concluir erroneamente que o defeito está melhorando."),
       opt("b","Porque a amplitude de GMF é sempre constante, independentemente da carga ou do tempo."),
       opt("c","Porque a GMF só pode ser medida uma única vez na vida útil do redutor."),
       opt("d","Porque a folga sempre aumenta a amplitude de GMF de forma linear e previsível com o tempo.")],
      "a",
      "Sendo um problema de folga, a amplitude de GMF diminui com o aumento de carga (o jogo se absorve quando as superfícies são pressionadas sob carga) — comparar leituras tomadas em condições de carga diferentes levaria a concluir, erroneamente, que o defeito está melhorando, quando na verdade não há relação com o tempo, apenas com a carga instantânea."),
    Q("No Caso 4, por que confiar apenas no espectro de velocidade em banda larga poderia atrasar a decisão de trocar o rolamento, e qual técnica antecipou o diagnóstico?",
      [opt("a","No Estágio 3 os picos já existem fisicamente mas podem ter amplitude baixa em banda larga, mascarados por outras fontes; a técnica de envelope (demodulação em torno de uma frequência de ressonância) isolou a modulação dos impactos e antecipou o diagnóstico."),
       opt("b","Porque o espectro de banda larga é sempre mais sensível que o envelope, mas mais lento de processar."),
       opt("c","Porque o envelope só pode ser calculado depois que o rolamento já falhou completamente."),
       opt("d","Não há diferença real de sensibilidade entre banda larga e envelope para defeitos de rolamento.")],
      "a",
      "No Estágio 3 os picos de defeito já existem fisicamente, mas podem ter amplitude relativamente baixa no espectro de velocidade em banda larga, mascarados por outras fontes de vibração — esperar que o defeito \"apareça\" ali pode significar aguardar até o Estágio 4. A técnica de envelope antecipou o diagnóstico ao isolar a modulação causada pelos impactos."),
    Q("No Caso 6, por que a solução não foi \"balancear o ventilador\" ou \"trocar o rolamento\", mesmo com vibração severa em BPF?",
      [opt("a","Porque o diagnóstico foi coincidência entre BPF e a frequência natural da base (ressonância estrutural) — a causa raiz está na estrutura, e balancear/trocar rolamento não mudaria a proximidade entre BPF e a frequência natural."),
       opt("b","Porque balancear ventiladores é sempre proibido por norma de segurança."),
       opt("c","Porque o rolamento já havia sido trocado recentemente, sem qualquer outra justificativa técnica."),
       opt("d","Porque a vibração severa em BPF sempre indica desbalanceamento do ventilador, que já havia sido corrigido antes.")],
      "a",
      "O diagnóstico (coincidência entre BPF e a frequência natural da base — ressonância estrutural) aponta a causa raiz na estrutura de suporte, não em um defeito interno do ventilador. Balancear ou trocar rolamento não mudaria a proximidade entre a frequência de excitação e a frequência natural, e a vibração severa retornaria."),
    Q("No Caso 8, por que a análise de banda estreita ao redor de 1X foi necessária, já que o espectro de banda larga parecia normal?",
      [opt("a","No estágio inicial de um problema de barras de rotor, as bandas laterais são estreitas e de baixa amplitude, facilmente escondidas dentro do lóbulo principal de 1X quando a resolução de banda larga é insuficiente."),
       opt("b","Porque o espectro de banda larga nunca é capaz de detectar problemas elétricos, apenas mecânicos."),
       opt("c","Porque a análise de banda estreita é sempre obrigatória por norma, independentemente do tipo de defeito."),
       opt("d","Porque bandas laterais só existem em análises de banda estreita, nunca aparecendo em banda larga sob nenhuma condição.")],
      "a",
      "No estágio inicial de um problema de barras de rotor, as bandas laterais são estreitas e de baixa amplitude, facilmente \"escondidas\" dentro do lóbulo principal do pico de 1X quando a resolução do espectro de banda larga é insuficiente — apenas a análise de banda estreita, com resolução fina ao redor de 1X, consegue separar essas bandas e confirmar o diagnóstico."),
    Q("No Caso 9, por que trocar o impelidor da bomba seria uma ação corretiva equivocada?",
      [opt("a","Porque a causa raiz foi hidráulica (NPSH insuficiente por baixa pressão de sucção); trocar o impelidor não eliminaria a cavitação, que voltaria a ocorrer assim que a condição de sucção insuficiente se repetisse."),
       opt("b","Porque impelidores de bombas centrífugas nunca podem ser substituídos em campo, apenas na fábrica."),
       opt("c","Porque a cavitação sempre desaparece sozinha após algumas semanas de operação, sem necessidade de intervenção."),
       opt("d","Porque o impelidor identificado como desgastado já havia sido trocado na semana anterior ao diagnóstico.")],
      "a",
      "A causa raiz identificada foi hidráulica (NPSH insuficiente por baixa pressão de sucção), não um defeito geométrico ou de desgaste do impelidor. Trocar o impelidor não eliminaria a cavitação — ele só deveria ser trocado se a inspeção revelasse erosão real já causada pela cavitação."),
    Q("Compare os Casos 3 e 10: ambos envolvem engrenagens e usam o espaçamento/período de um sinal para identificar o eixo problemático. Qual é a diferença fundamental entre os dois diagnósticos?",
      [opt("a","O Caso 3 usa o espaçamento das bandas laterais no espectro (frequência) para identificar folga distribuída dependente de carga; o Caso 10 usa o período entre impactos na forma de onda no tempo para identificar um dente trincado, defeito discreto e localizado."),
       opt("b","Não há diferença real — ambos os casos usam exatamente a mesma técnica e chegam à mesma conclusão."),
       opt("c","O Caso 3 usa forma de onda no tempo; o Caso 10 usa exclusivamente o espectro em frequência."),
       opt("d","Ambos os casos dependem exclusivamente de medições de temperatura do redutor, sem uso de vibração.")],
      "a",
      "No Caso 3, o raciocínio usa o espaçamento das bandas laterais no espectro (frequência) para identificar o pinhão como fonte de modulação por folga — um defeito distribuído e dependente de carga. No Caso 10, o raciocínio usa o período entre impactos na forma de onda no tempo para identificar o eixo de saída como portador de um dente trincado — um defeito discreto e localizado, mais bem revelado no domínio do tempo."),
]

CONVERTED["m18"] = [
    Q("Em qual estágio de falha de rolamento o defeito só é detectável pelo envelope de aceleração, sem alteração perceptível em velocidade ou aceleração pura?",
      [opt("a","Estágio 1 — defeito submicroscópico, libera energia de impacto em frequência alta demais para aparecer em velocidade/aceleração pura; só o envelope demodula essa energia."),
       opt("b","Estágio 2 — quando já há bandas laterais visíveis diretamente no espectro de velocidade."),
       opt("c","Estágio 3 — quando os picos discretos de BPFO/BPFI já dominam o espectro de velocidade."),
       opt("d","Estágio 4 — quando o piso de ruído já está elevado em qualquer parâmetro medido.")],
      "a",
      "No Estágio 1, o defeito é submicroscópico e libera energia de impacto em frequência alta demais para aparecer em velocidade/aceleração pura; só o envelope de aceleração demodula essa energia."),
    Q("Que padrão no espectro indica desgaste progressivo num engrenamento, e em que ordem (múltiplo de RPM) ele aparece?",
      [opt("a","A frequência de engrenamento (GMF), na ordem igual ao número de dentes do componente modulador, cercada por bandas laterais espaçadas na rotação desse mesmo eixo."),
       opt("b","Um pico isolado exatamente em 1X RPM, sem qualquer banda lateral associada."),
       opt("c","Um piso de ruído aleatório de banda larga, sem nenhum pico discreto identificável."),
       opt("d","Um pico exclusivamente na frequência de linha elétrica (50/60 Hz), independentemente da rotação.")],
      "a",
      "O desgaste progressivo aparece na frequência de engrenamento (GMF), na ordem igual ao número de dentes do componente modulador (pinhão ou coroa), cercada por bandas laterais espaçadas na rotação desse mesmo eixo."),
    Q("Como diferenciar, pela leitura do envelope de aceleração, um defeito de rolamento avançado de um defeito elétrico nas barras do rotor?",
      [opt("a","No defeito de rolamento avançado, o envelope fica muito elevado; no defeito elétrico de barras do rotor, o envelope permanece normal mesmo com bandas laterais visíveis em 1X."),
       opt("b","Ambos elevam o envelope de aceleração exatamente na mesma proporção, tornando-os indistinguíveis."),
       opt("c","O defeito elétrico sempre eleva o envelope mais do que o defeito de rolamento."),
       opt("d","O envelope de aceleração não consegue detectar nenhum dos dois tipos de defeito.")],
      "a",
      "No defeito de rolamento avançado, o envelope de aceleração fica muito elevado; no defeito elétrico de barras do rotor, o envelope permanece normal, mesmo com bandas laterais visíveis em 1X — a origem ali é elétrica, não mecânica."),
]

CONVERTED["m19"] = [
    Q("Por que a zona de carga de um rolamento sob carga radial constante sempre se concentra no anel ESTACIONÁRIO, e não no anel que gira?",
      [opt("a","Porque cada ponto do anel girante passa pela zona de carga a cada volta, distribuindo o desgaste por toda a circunferência; o anel estacionário recebe sempre a carga na mesma posição, concentrando o desgaste numa faixa fixa e estreita."),
       opt("b","Porque o anel girante é sempre fabricado com material mais resistente que o anel estacionário."),
       opt("c","Porque a carga radial só atua fisicamente sobre o anel estacionário, nunca sobre o anel girante."),
       opt("d","Porque o anel estacionário gira em sentido oposto ao anel girante, dobrando a carga recebida.")],
      "a",
      "Cada ponto do anel girante passa pela zona de carga a cada volta, distribuindo o desgaste por toda a circunferência com largura uniforme; o anel estacionário recebe sempre a carga na mesma posição, concentrando o desgaste numa faixa fixa e mais estreita."),
    Q("Um padrão de pista alarga-se e passa a ocupar quase toda a circunferência, migrando de um lado para o outro. Qual é a causa mais provável, e o que deve ser verificado?",
      [opt("a","Desalinhamento entre eixo e mancal — verificar perpendicularidade dos encostos (abutments), empenamento do eixo e alinhamento geral do acoplamento."),
       opt("b","Desbalanceamento do rotor — verificar apenas a massa de correção necessária."),
       opt("c","Lubrificação em excesso — verificar apenas a quantidade de graxa aplicada."),
       opt("d","Corrosão por umidade — verificar apenas a vedação do mancal contra a entrada de água.")],
      "a",
      "É o padrão típico de desalinhamento entre eixo e mancal. Deve-se verificar a perpendicularidade dos encostos (abutments), o empenamento do eixo e o alinhamento geral do acoplamento."),
    Q("Por que a técnica de envelope de aceleração oferece um tempo de pré-aviso maior do que a inspeção por \"ouvir e sentir\" a máquina?",
      [opt("a","Porque demodula impactos de alta frequência liberados por microlascamentos ainda submicroscópicos, detectando o Estágio 2 de dano — muito antes de haver ruído ou vibração perceptível ao ouvido/tato humano, que só ocorrem em estágios avançados."),
       opt("b","Porque o ouvido humano é fisicamente incapaz de perceber qualquer som acima de 1000 Hz."),
       opt("c","Porque a inspeção por \"ouvir e sentir\" só é válida em rolamentos novos, nunca em rolamentos usados."),
       opt("d","Porque o envelope de aceleração e a inspeção sensorial detectam exatamente o mesmo estágio de dano.")],
      "a",
      "O envelope de aceleração demodula impactos de alta frequência liberados por microlascamentos ainda submicroscópicos, detectando o Estágio 2 de dano — muito antes de haver ruído ou vibração perceptível ao ouvido humano ou alteração perceptível ao tato (que só ocorrem em estágios avançados, 3 ou 4)."),
]

CONVERTED["m20"] = [
    Q("Qual é a diferença fundamental entre fadiga subsuperficial e fadiga superficial, na origem da trinca e na causa mais comum?",
      [opt("a","Subsuperficial nasce abaixo da superfície por tensão cíclica de cisalhamento, mesmo com lubrificação adequada (modo \"natural\" que define a vida calculada); superficial nasce na superfície, causada por lubrificação inadequada que permite contato direto entre asperezas, podendo ocorrer antes da vida calculada."),
       opt("b","Não há diferença real entre os dois tipos — são apenas nomes distintos para o mesmo mecanismo de falha."),
       opt("c","Subsuperficial é sempre causada por contaminação por água; superficial é sempre causada por sobrecarga mecânica."),
       opt("d","Superficial nasce sempre abaixo da superfície; subsuperficial nasce sempre na superfície de contato.")],
      "a",
      "A fadiga subsuperficial nasce abaixo da superfície (tipicamente 0,1–0,5 mm), por tensão cíclica de cisalhamento, mesmo com lubrificação adequada — é o modo de falha \"natural\" que define a vida calculada. A fadiga superficial nasce diretamente na superfície, causada por lubrificação inadequada que permite contato direto entre asperezas (microslip), podendo ocorrer bem antes da vida calculada."),
    Q("Por que o desgaste por polimento (polishing wear), que deixa a pista com aparência de espelho, é enganoso para quem não conhece o fenômeno?",
      [opt("a","Porque a aparência de espelho parece indicar superfície bem-acabada/saudável, quando na verdade resulta de partículas abrasivas finas com filme de óleo fino demais, alterando e destruindo lentamente a geometria original."),
       opt("b","Porque o desgaste por polimento só ocorre em rolamentos novos, nunca em rolamentos usados."),
       opt("c","Porque essa aparência sempre indica excesso de lubrificação, nunca deficiência de filme."),
       opt("d","Porque não existe relação entre a aparência da pista e o real estado de desgaste do rolamento.")],
      "a",
      "A aparência de espelho parece indicar uma superfície \"bem-acabada\" ou saudável, quando na verdade resulta de partículas abrasivas finas combinadas com um filme de óleo fino demais, alterando (e destruindo lentamente) a geometria original da pista — o oposto de uma condição saudável."),
    Q("Como diferenciar, na inspeção visual, false brinelling de erosão elétrica por corrente de fuga, já que ambos produzem sulcos no espaçamento dos elementos rolantes?",
      [opt("a","False brinelling ocorre com a máquina parada e exposta a vibração externa (causa mecânica); erosão elétrica ocorre com a máquina em operação e está associada a problemas elétricos — a confirmação exige verificar o sistema elétrico e o histórico de operação."),
       opt("b","False brinelling só ocorre em rolamentos de esferas; erosão elétrica só ocorre em rolamentos de rolos."),
       opt("c","A cor da graxa ao redor do rolamento diferencia definitivamente os dois mecanismos, sem necessidade de outra verificação."),
       opt("d","Não existe forma de diferenciar os dois mecanismos, mesmo com análise elétrica ou de histórico.")],
      "a",
      "A diferença está na causa e no contexto: false brinelling ocorre com a máquina parada e exposta a vibração externa (fonte puramente mecânica); a erosão por corrente de fuga ocorre com a máquina em operação e está associada a problemas elétricos (aterramento, isolação, conversor de frequência). A confirmação definitiva costuma exigir verificar o sistema elétrico e o histórico de operação."),
]

CONVERTED["m21"] = [
    Q("Um rolamento apresenta sulcos paralelos (fluting) na pista, parecidos com false brinelling. Que evidência de corte transversal confirmaria erosão elétrica por corrente de fuga, e não false brinelling?",
      [opt("a","Uma camada branca reendurecida (66-68 HRC) sobre uma camada escura recozida (56-57 HRC) — assinatura térmica de passagem de corrente elétrica, que false brinelling (puramente mecânico) não produz."),
       opt("b","Uma coloração azulada uniforme em toda a pista, sem variação de dureza entre camadas."),
       opt("c","A ausência total de qualquer alteração de dureza, já que ambos os mecanismos produzem exatamente a mesma metalurgia."),
       opt("d","Uma camada de óxido vermelho (ferrugem) espessa cobrindo toda a superfície da pista.")],
      "a",
      "Um corte transversal mostrando uma camada branca reendurecida (66-68 HRC) sobre uma camada escura recozida (56-57 HRC) é assinatura térmica de passagem de corrente elétrica — false brinelling, sendo puramente mecânico (micromovimento sob vibração), não produz essa alteração de dureza por calor."),
    Q("Qual é a diferença de aparência entre fratura por fadiga e fratura forçada, e por que essa diferença importa para a investigação?",
      [opt("a","Fadiga mostra marcas de praia concêntricas (propagação lenta e progressiva sob flexão cíclica); fratura forçada é irregular e única (evento único de sobtensão) — a diferença aponta causas distintas: problema recorrente de projeto/carga vs. evento isolado de manuseio."),
       opt("b","Ambas produzem exatamente a mesma aparência visual, tornando a distinção impossível sem ensaio metalográfico."),
       opt("c","Fratura por fadiga é sempre instantânea; fratura forçada é sempre um processo lento e progressivo."),
       opt("d","A diferença de aparência não tem nenhuma relevância prática para a investigação da causa raiz.")],
      "a",
      "A fratura por fadiga mostra \"marcas de praia\" concêntricas, resultado da propagação lenta e progressiva de uma trinca sob flexão cíclica repetida; a fratura forçada é irregular e única, resultado de um evento único de sobtensão além do limite de resistência do material. A diferença aponta causas completamente distintas: fadiga sugere problema recorrente de projeto/carga; forçada sugere evento isolado de manuseio ou montagem."),
    Q("No caso do moinho de argila, cite evidências físicas (além da falha prematura) que confirmaram desgaste e movimento anormais no rolamento.",
      [opt("a","Folga radial interna medida (0,900 mm) muito acima da faixa de um rolamento novo (0,250–0,320 mm), e desgaste nos bolsões da gaiola tão grande que os elementos rolantes caíam ao balançar o anel interno — além da corrosão por fretting no anel externo."),
       opt("b","Apenas a cor do óleo lubrificante, sem qualquer medição dimensional do rolamento."),
       opt("c","Apenas o ruído audível reportado pelo operador durante a última semana de operação."),
       opt("d","Apenas a temperatura superficial do mancal registrada no dia da falha.")],
      "a",
      "A folga radial interna medida (0,900 mm) estava muito acima da faixa de um rolamento novo (0,250–0,320 mm), confirmando desgaste acumulado severo; e o desgaste nos bolsões da gaiola era tão grande que os elementos rolantes caíam dos bolsões ao simplesmente balançar o anel interno — ambas evidências físicas diretas, além da corrosão por fretting no anel externo."),
]

with open("/tmp/_quiz_conversion_2.json", "w", encoding="utf-8") as f:
    json.dump(CONVERTED, f, ensure_ascii=False)
print("OK — módulos convertidos:", list(CONVERTED.keys()))
total = sum(len(v) for v in CONVERTED.values())
print("total perguntas convertidas nesta parte:", total)
