// Casos adicionais — Centrífugas, Bombas Centrífugas e Bombas de Vácuo.
// Seguem exatamente o schema de data/cases.js (ver CASES nesse arquivo).
const EXTRA_CASES = [
  {
    id: "c16",
    num: 16,
    level: "intermediário",
    title: "Centrífuga industrial: \"está vibrando muito\" — mas é mesmo desbalanceamento?",
    briefing: [
      "Centrífuga de cesto para desidratação de polpa de celulose, 1180 rpm, mancais de rolamento nas duas extremidades do eixo.",
      "O operador reportou apenas: \"a centrífuga está vibrando muito, principalmente depois que carregamos um lote novo\" — sem mais detalhes técnicos.",
      "Medição radial no mancal superior: pico dominante em 1X RPM, com amplitude quase idêntica nas direções horizontal e vertical, e fase estável e repetível entre partidas sucessivas.",
    ],
    readings: { temp: 44, vel: 6.9, accel: 0.7, envelope: 0.14 },
    spectrum: { mode: "freq", xmax: 5, unit: "Ordens (x RPM)", peaks: [{ order: 1, amp: 1.0 }, { order: 2, amp: 0.1 }, { order: 3, amp: 0.06 }] },
    trend: { unit: "mm/s RMS", months: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun"], values: [2.8, 3.1, 3.9, 4.8, 5.9, 6.9], alertLimit: 4.5, dangerLimit: 7.1 },
    diagnosisOptions: [
      { id: "a", text: "Desbalanceamento de massa (provavelmente o cesto com carga distribuída de forma desigual)" },
      { id: "b", text: "Defeito de rolamento em estágio avançado" },
      { id: "c", text: "Folga mecânica na fixação do mancal" },
      { id: "d", text: "Ressonância estrutural da base" },
    ],
    correctDiagnosis: "a",
    checks: [
      { id: "order", label: "Ordem do pico dominante (xRPM)", type: "numeric", correct: 1, tolerance: 0.15 },
      { id: "env", label: "O envelope de aceleração está elevado (indicando defeito de rolamento associado)?", type: "mc", options: [{ id: "sim", text: "Sim, bem acima do normal" }, { id: "nao", text: "Não, dentro da faixa normal" }], correct: "nao" },
    ],
    hint: "Dica: a queixa do operador (\"vibrando muito\") é apenas um SINTOMA, não um diagnóstico — o comentário sobre \"depois que carregamos um lote novo\" é a pista mais forte. Verifique se o pico dominante é 1X, com amplitude parecida nas duas direções radiais e fase estável — e se o envelope de aceleração (que apontaria defeito de rolamento) está normal ou elevado.",
    explanation: "\"Vibrando muito\" é a queixa do operador, não o diagnóstico — o trabalho do analista é traduzir esse sintoma num espectro. Aqui, 1X domina com amplitude semelhante nas duas direções radiais e fase estável entre partidas: assinatura clássica de desbalanceamento de massa (Módulo 6.1), plausivelmente por uma distribuição desigual do lote de celulose no cesto. O envelope de aceleração normal descarta um defeito de rolamento como causa — importante não pular direto para \"deve ser o rolamento\" só porque o mancal é o ponto de medição.",
    action: "Ação recomendada: balanceamento de campo em um plano (Módulo 14) e revisão do procedimento de carregamento do cesto para distribuir o lote de forma mais uniforme.",
  },
  {
    id: "c17",
    num: 17,
    level: "avançado",
    title: "Centrífuga industrial com defeito de rolamento em estágio inicial",
    briefing: [
      "Centrífuga decantadora de uma estação de tratamento de efluentes, 3550 rpm, rolamentos de rolos cônicos.",
      "Vibração global (velocidade RMS) ainda dentro da faixa normal, sem queixa perceptível do operador.",
      "O envelope de aceleração, monitorado mensalmente, subiu de forma consistente nos últimos três meses, com um pico discreto no espectro de envelope próximo à frequência de defeito de pista interna (BPFI) calculada.",
    ],
    readings: { temp: 47, vel: 2.4, accel: 0.5, envelope: 0.42 },
    spectrum: { mode: "freq", xmax: 6, unit: "Ordens (x RPM) — espectro de envelope (gE)", peaks: [{ order: 4.1, amp: 0.65 }, { order: 1, amp: 0.12 }], noise: 0.05 },
    trend: { unit: "gE Pk-Pk", months: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun"], values: [0.13, 0.14, 0.19, 0.26, 0.33, 0.42], alertLimit: 0.3, dangerLimit: 0.6 },
    diagnosisOptions: [
      { id: "a", text: "Defeito de rolamento em estágio inicial (Estágio 1-2)" },
      { id: "b", text: "Desbalanceamento de massa" },
      { id: "c", text: "Máquina normal, sem defeito" },
      { id: "d", text: "Cavitação no processo" },
    ],
    correctDiagnosis: "a",
    checks: [
      { id: "qual", label: "Qual leitura já ultrapassou o limite de alerta?", type: "mc", options: [{ id: "vel", text: "Velocidade (mm/s)" }, { id: "env", text: "Envelope de aceleração (gE)" }], correct: "env" },
      { id: "acao", label: "Urgência de intervenção neste estágio", type: "mc", options: [{ id: "parar", text: "Parar a máquina imediatamente" }, { id: "planejar", text: "Aumentar frequência de monitoramento e planejar substituição" }], correct: "planejar" },
    ],
    hint: "Dica: repare que a velocidade global ainda está normal — se você olhasse só para ela, diria que a máquina está saudável. É exatamente por isso que o envelope de aceleração existe: ele antecipa a detecção antes que o defeito apareça em velocidade (Módulo 7 e Módulo 19.3).",
    explanation: "Velocidade de vibração normal, mas envelope de aceleração em tendência de alta consistente, com pico discreto próximo à BPFI calculada: assinatura de defeito de rolamento em estágio inicial (Estágios 1-2 do Módulo 19.3) — o tipo de achado que só aparece porque a planta monitora envelope de aceleração, não apenas velocidade global.",
    action: "Ação recomendada: aumentar a frequência de monitoramento por envelope, programar a substituição do rolamento na próxima janela de manutenção, e evitar aguardar o defeito evoluir para os estágios 3-4.",
  },
  {
    id: "c18",
    num: 18,
    level: "intermediário",
    title: "Bomba centrífuga com vórtice de sucção por baixa submergência",
    briefing: [
      "Bomba centrífuga alimentando um poço de sucção com nível de líquido variável, associado à demanda do processo a jusante.",
      "Ruído de banda larga sobreposto ao espectro, mais intenso quando o nível do poço fica abaixo de um determinado ponto — a equipe de operação confirma que, nesses períodos, é possível ver um vórtice de ar se formando na superfície do poço, próximo à tomada de sucção.",
      "Aceleração e envelope de aceleração elevados, mas sem os harmônicos discretos e regulares característicos de um defeito de rolamento.",
    ],
    readings: { temp: 46, vel: 4.2, accel: 2.6, envelope: 1.1 },
    spectrum: { mode: "freq", xmax: 10, unit: "Ordens (x RPM)", peaks: [{ order: 1, amp: 0.3 }, { order: 2, amp: 0.15 }], noise: 0.7 },
    trend: { unit: "mm/s RMS", months: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun"], values: [2.0, 2.3, 2.9, 3.4, 3.8, 4.2], alertLimit: 4.5, dangerLimit: 7.1 },
    diagnosisOptions: [
      { id: "a", text: "Cavitação por vórtice de sucção (baixa submergência)" },
      { id: "b", text: "Defeito de rolamento" },
      { id: "c", text: "Desbalanceamento de massa" },
      { id: "d", text: "Desalinhamento angular" },
    ],
    correctDiagnosis: "a",
    checks: [
      { id: "correlacao", label: "O ruído de banda larga está correlacionado com o quê?", type: "mc", options: [{ id: "nivel", text: "Nível do poço de sucção" }, { id: "temp", text: "Temperatura ambiente" }], correct: "nivel" },
      { id: "padrao", label: "O ruído forma harmônicos discretos e regulares (como um defeito de rolamento)?", type: "mc", options: [{ id: "sim", text: "Sim" }, { id: "nao", text: "Não, é ruído de banda larga sem padrão fixo" }], correct: "nao" },
    ],
    hint: "Dica: assim como na cavitação por NPSH insuficiente (Módulo 11.2), o ruído de banda larga aqui também está ligado a bolhas de ar/vapor implodindo — mas repare na causa raiz específica mencionada no briefing: um vórtice visível na superfície do poço, e não a pressão de sucção do sistema.",
    explanation: "Ruído de banda larga que varia com o nível do poço de sucção, sem os harmônicos discretos característicos de rolamento, é a assinatura de cavitação por vórtice de sucção: quando a submergência da tomada de sucção é insuficiente, um vórtice de ar se forma e é arrastado para dentro da bomba, colapsando (implodindo) de forma semelhante às bolhas de vapor da cavitação por NPSH — mas aqui a causa raiz é o nível operacional do poço, não a pressão de sucção do sistema em si (Módulo 11.2).",
    action: "Ação recomendada: revisar o nível mínimo operacional do poço de sucção, considerar instalar um defletor ou dispositivo antivórtice, e evitar operar abaixo da submergência mínima especificada pelo fabricante da bomba.",
  },
  {
    id: "c19",
    num: 19,
    level: "avançado",
    title: "Bomba centrífuga: golpe de aríete interferindo na leitura de vibração",
    briefing: [
      "Bomba centrífuga de uma linha de recalque com uma válvula de bloqueio de fechamento rápido logo a jusante, operada em ciclos automáticos pelo sistema de controle.",
      "A leitura pontual de vibração, feita logo após um fechamento da válvula, mostrou um pico de amplitude muito alto e inconsistente — a medição seguinte, poucos minutos depois, voltou a valores normais sem nenhuma intervenção de manutenção.",
      "O padrão não se repete de forma consistente entre medições sucessivas, e os horários dos picos coincidem com os registros de fechamento da válvula no sistema de controle (SCADA).",
    ],
    readings: { temp: 41, vel: 9.5, accel: 1.2, envelope: 0.2 },
    spectrum: { mode: "freq", xmax: 8, unit: "Ordens (x RPM)", peaks: [{ order: 1, amp: 0.25 }, { order: 2.3, amp: 0.2 }, { order: 5.7, amp: 0.3 }], noise: 0.9 },
    trend: { unit: "mm/s RMS", months: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun"], values: [2.6, 8.9, 2.4, 9.1, 2.5, 9.5], alertLimit: 4.5, dangerLimit: 7.1 },
    diagnosisOptions: [
      { id: "a", text: "Golpe de aríete (evento transitório de processo, não defeito mecânico)" },
      { id: "b", text: "Defeito de rolamento em estágio avançado" },
      { id: "c", text: "Desbalanceamento severo" },
      { id: "d", text: "Folga mecânica estrutural" },
    ],
    correctDiagnosis: "a",
    checks: [
      { id: "repete", label: "O padrão se repete de forma consistente entre medições sucessivas?", type: "mc", options: [{ id: "sim", text: "Sim, sempre no mesmo nível" }, { id: "nao", text: "Não, varia muito entre medições" }], correct: "nao" },
      { id: "correlacao", label: "Os picos de vibração coincidem com quê, segundo o SCADA?", type: "mc", options: [{ id: "valvula", text: "Horários de fechamento da válvula de bloqueio" }, { id: "temp", text: "Horários de troca de turno" }], correct: "valvula" },
    ],
    hint: "Dica: compare este caso com o do rolamento em estágio avançado (Módulo 19) — lá, o padrão é ESTÁVEL e se repete a cada medição, com uma tendência de piora consistente ao longo do tempo. Aqui, os valores oscilam bruscamente entre medições consecutivas (2,6 → 8,9 → 2,4 → 9,1...), sem uma tendência real de piora — e coincidem com um evento externo do processo.",
    explanation: "O ponto-chave deste caso é a INCONSISTÊNCIA: um defeito mecânico real (rolamento, desbalanceamento, folga) produz um padrão estável e repetível, com tendência de piora ao longo do tempo. Aqui, os valores oscilam bruscamente entre medições sem tendência real, e coincidem exatamente com os horários de fechamento da válvula de bloqueio registrados no SCADA — a assinatura de um evento transitório de processo (golpe de aríete), não de um defeito mecânico na bomba ou no rolamento. Tratar isso como defeito de rolamento levaria a uma troca desnecessária, sem resolver o problema real.",
    action: "Ação recomendada: revisar a lógica de fechamento da válvula (tempo de fechamento mais gradual), avaliar a instalação de um dispositivo de alívio (válvula de alívio ou tanque hidropneumático) na linha, e não tratar como defeito mecânico da bomba antes de descartar a causa de processo.",
  },
  {
    id: "c20",
    num: 20,
    level: "intermediário",
    title: "Bomba centrífuga com defeito de rolamento no lado do acoplamento",
    briefing: [
      "Bomba centrífuga de processo, 2960 rpm, rolamento rígido de esferas no lado acoplado ao motor.",
      "BPFO calculado para este rolamento: 4,7X RPM.",
      "Espectro de envelope de aceleração mostra pico discreto bem definido em 4,7X RPM, com bandas laterais espaçadas em 1X RPM ao redor.",
    ],
    readings: { temp: 58, vel: 5.1, accel: 2.2, envelope: 1.3 },
    spectrum: { mode: "freq", xmax: 10, unit: "Ordens (x RPM) — espectro de envelope (gE)", peaks: [{ order: 3.7, amp: 0.2 }, { order: 4.7, amp: 0.75 }, { order: 5.7, amp: 0.2 }, { order: 9.4, amp: 0.3 }], noise: 0.08 },
    trend: { unit: "gE Pk-Pk", months: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun"], values: [0.2, 0.3, 0.45, 0.7, 1.0, 1.3], alertLimit: 0.3, dangerLimit: 0.6 },
    diagnosisOptions: [
      { id: "a", text: "Defeito de rolamento — pista externa (BPFO), estágio estabelecido" },
      { id: "b", text: "Cavitação" },
      { id: "c", text: "Desalinhamento angular" },
      { id: "d", text: "Golpe de aríete" },
    ],
    correctDiagnosis: "a",
    checks: [
      { id: "order", label: "Ordem do pico dominante no envelope (xRPM)", type: "numeric", correct: 4.7, tolerance: 0.2 },
      { id: "banda", label: "As bandas laterais ao redor do pico principal estão espaçadas em quê?", type: "mc", options: [{ id: "1x", text: "1X RPM do eixo" }, { id: "2x", text: "2X RPM do eixo" }], correct: "1x" },
    ],
    hint: "Dica: o valor calculado da BPFO (4,7X) bate exatamente com a ordem do pico dominante no envelope — e o envelope já ultrapassou bastante o limite de alerta, com tendência de piora consistente ao longo de seis meses (não uma oscilação abrupta como no golpe de aríete).",
    explanation: "Pico discreto em 4,7X RPM (a BPFO calculada para este rolamento), cercado por bandas laterais em 1X RPM, com envelope de aceleração em tendência de alta consistente e já bem acima do limite de alerta: assinatura clara de defeito de pista externa (BPFO) já em estágio estabelecido (Módulo 7.4). Diferente do golpe de aríete (Estudo de Caso c19), aqui a tendência é estável e consistentemente crescente, não uma oscilação abrupta.",
    action: "Ação recomendada: planejar a substituição do rolamento do lado acoplado na próxima janela de manutenção disponível, e verificar a lubrificação para descartar contribuição adicional.",
  },
  {
    id: "c21",
    num: 21,
    level: "avançado",
    title: "Bomba de vácuo com defeito de rolamento por contaminação de processo",
    briefing: [
      "Bomba de vácuo de anel líquido, usada numa linha de embalagem a vácuo de uma planta de alimentos, 1750 rpm.",
      "Processo tem histórico de arraste de partículas finas do produto para dentro do sistema de vácuo, apesar do filtro de linha instalado.",
      "Envelope de aceleração elevado, com pico discreto próximo à frequência de defeito de pista interna (BPFI) calculada, e leve aumento de temperatura em relação ao histórico.",
    ],
    readings: { temp: 52, vel: 3.8, accel: 1.6, envelope: 0.85 },
    spectrum: { mode: "freq", xmax: 8, unit: "Ordens (x RPM) — espectro de envelope (gE)", peaks: [{ order: 5.2, amp: 0.6 }, { order: 1, amp: 0.15 }, { order: 6.2, amp: 0.2 }], noise: 0.1 },
    trend: { unit: "gE Pk-Pk", months: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun"], values: [0.18, 0.22, 0.31, 0.48, 0.65, 0.85], alertLimit: 0.3, dangerLimit: 0.6 },
    diagnosisOptions: [
      { id: "a", text: "Defeito de rolamento — pista interna (BPFI), provavelmente por contaminação" },
      { id: "b", text: "Cavitação no anel líquido" },
      { id: "c", text: "Desbalanceamento do rotor" },
      { id: "d", text: "Golpe de aríete na linha de vácuo" },
    ],
    correctDiagnosis: "a",
    checks: [
      { id: "order", label: "Ordem do pico dominante no envelope (xRPM)", type: "numeric", correct: 5.2, tolerance: 0.2 },
      { id: "causa", label: "Causa raiz mais provável, dado o histórico do processo", type: "mc", options: [{ id: "contam", text: "Contaminação por partículas finas do produto" }, { id: "eletrico", text: "Problema elétrico no motor de acionamento" }], correct: "contam" },
    ],
    hint: "Dica: o histórico do processo (arraste de partículas finas, apesar do filtro) é a pista mais forte sobre a causa raiz — pense em qual modo de falha do Módulo 20 está associado a partículas sólidas contaminando o rolamento.",
    explanation: "Pico discreto na BPFI calculada, com envelope de aceleração em tendência de alta consistente e leve aumento de temperatura: defeito de rolamento (pista interna) em evolução. Dado o histórico de arraste de partículas finas do produto para o sistema de vácuo, a causa raiz mais provável é contaminação do lubrificante por partículas sólidas — o mesmo mecanismo de indentação por partículas detalhado no Módulo 21.2.2, que inicia fadiga prematura a partir de uma indentação na pista.",
    action: "Ação recomendada: revisar a eficácia do filtro de linha e da vedação do rolamento contra o ambiente de processo, e programar a substituição do rolamento antes que o defeito evolua para estágios mais avançados.",
  },
];
